services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: portfolio-backend-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - spring-cache-prod:/root/.m2
    environment:
      SPRING_BOOT_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_BOOT_DEVTOOLS_RESTART_TRIGGER_FILE: "pom.xml"
    env_file:
      - ./.env
    dns:
      - 8.8.8.8
      - 1.1.1.1 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: portfolio-frontend-prod
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_started

volumes:
  spring-cache-prod: